services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    working_dir: /app/medusa-store
    command: pnpm dev
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app/medusa-store-storefront
    command: pnpm dev
    environment:
      - NODE_ENV=development